3d tsdf slices
tu-darmstadt-ros-pkg/cartographer_ros pull request #4
Opened 2021-09-29 08:11 UTC by bhirschel

Adds a TSDF visualization as 3 planar slices, as requested in [Task #2947: Cartographer 3D Environment Model Rendering](https://redmine.sim.informatik.tu-darmstadt.de/issues/2957). The x, y and z-position can either be fixated on the robots current position or set manually via dynamic_reconfigure

2021-10-18 20:29 UTC, kdaun requested changes
Looks mostly good to me. Thanks!
I noticed a few usages of auto where we should be able to avoid copying the data which partially already added in the last PR. Please check them.

2021-10-18 20:29 UTC, kdaun commented on cartographer_ros/cartographer_ros/map_builder_bridge.cc
>      auto local_trajectory_data = GetLocalTrajectoryData();
As you only need read access, `auto const &` instead of `auto` should be sufficient and avoid the copy.

2021-10-18 20:29 UTC, kdaun commented on cartographer_ros/cartographer_ros/map_builder_bridge.cc
>      auto robot_position = local_trajectory_data[0].local_slam_data->local_pose.translation();
check auto const &

2021-10-18 20:29 UTC, kdaun commented on cartographer_ros/cartographer_ros/map_builder_bridge.cc
>      auto local_trajectory_data = GetLocalTrajectoryData();
check auto const &

2021-10-18 20:29 UTC, kdaun commented on cartographer_ros/cartographer_ros/map_builder_bridge.cc
>      auto robot_position = local_trajectory_data[0].local_slam_data->local_pose.translation();
check auto const &

2021-10-18 20:29 UTC, kdaun commented on cartographer_ros/cartographer_ros/map_builder_bridge.cc
> +    auto local_trajectory_data = GetLocalTrajectoryData();
check auto const &

2021-10-18 20:29 UTC, kdaun commented on cartographer_ros/cartographer_ros/map_builder_bridge.cc
> +    auto robot_position = local_trajectory_data[0].local_slam_data->local_pose.translation();
check auto const &

2021-10-19 14:28 UTC, bhirschel commented
This is fixed for now but needs testing

2021-10-22 08:44 UTC, bhirschel commented
Implemented and tested const auto reference instead of a copy of the data

2021-10-22 08:58 UTC, merged